### ISSUE TITLE
SDK requirements

### ISSUE THREAD

**Issue by TheWhiteLlama** [pavlospt/RxIAPv3#1]
Hi there! Is there a reason why the library is just for SDK 19+?
I thought there wasn't anything at all in RX that blocks users from using RX with SDK 10+?

I guess there might be another reason for that?

**Comment by pavlospt** [comment]
You can use it on lower versions as well. This is cause of development speed. Will lower it down on the next release.

**Comment by TheWhiteLlama** [comment]
@pavlospt Hey thanks for that quick answer! Alright, for now I will overwrite the sdk min version :+1:
